  rules:
  - host: prometheus.ijuned.com
    http:
      paths:
      - path: /
        backend:
          serviceName: prometheus
          servicePort: 9090
  - host: alertmanager.ijuned.com
    http:
      paths:
      - path: /
        backend:
          serviceName: alertmanager
          servicePort: 9093
  - host: grafana.ijuned.com
    http:
      paths:
      - path: /
        backend:
          serviceName: grafana
          servicePort: 3000
