apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  ports:
    # the port that this service should serve on
  - port: 3000
    targetPort: 3000
  selector:
    app: grafana

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grafana-master
  # these labels can be applied automatically
  # from the labels in the pod template if not set
  # labels:
  #   app: grafana
  #   role: master
  #   tier: backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: master
        image: grafana/grafana
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 3000
